# Generated by Django 3.1.4 on 2021-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
