# Generated by Django 3.1.4 on 2021-11-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211118_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
