# Generated by Django 3.2.9 on 2021-11-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='month',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
